version: "3"
services:
  backend-strapi:
    container_name: backend-strapi
    build:
      context: ./baas-strapi-docker
      dockerfile: ./Dockerfile
    image: baas_strapi
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./baas-strapi-docker/config:/opt/app/config
      - ./baas-strapi-docker/src:/opt/app/src
      - ./baas-strapi-docker/package.json:/opt/package.json
      - ./baas-strapi-docker/package.json.lock:/opt/yarn.lock
      - ./baas-strapi-docker/.env:/opt/app/.env
      - ./baas-strapi-docker/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - backend-db

  backend-db:
    container_name: backend-db
    platform: linux/amd64 # for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:16.2-alpine3.19
    volumes:
      - backend-db-volume:/var/lib/postgresql/data/ # using a volume
    ports:
      - "5432:5432"
    networks:
      - strapi

  backend-test:
    build:
      context: ./baas-strapi-docker
      dockerfile: Dockerfile.test
    command: ["npm", "test"]

volumes:
  backend-db-volume:

networks:
  strapi:
    name: Strapi
    driver: bridge