version: "3"
services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    image: baas_frontend
    restart: unless-stopped
    ports: 
      - "4200:80"
    networks:
      - strapi
    depends_on:
      - strapi

  frontend-test:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.test

  strapi:
    container_name: strapi
    build:
      context: ./baas-strapi-docker
      dockerfile: ./Dockerfile
    image: baas_strapi
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./baas-strapi-docker/config:/opt/app/config
      - ./baas-strapi-docker/src:/opt/app/src
      - ./baas-strapi-docker/package.json:/opt/package.json
      - ./baas-strapi-docker/package.json.lock:/opt/yarn.lock
      - ./baas-strapi-docker/.env:/opt/app/.env
      - ./baas-strapi-docker/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 # for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ # using a volume
    ports:
      - "5432:5432"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge