{
 "title": "Observability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(http_requests_total) / sum(http_request_duration_seconds_sum)",
     "legendFormat": "/"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    { "expr": "increase(revenue[1h])", "legendFormat": "Revenue" }
   ]
  },
  {
   "title": "Order",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Orders" } },
   "targets": [
    { "expr": "increase(orders[1h])", "legendFormat": "Revenue" }
   ]
  },
  {
   "title": "Revenue per Order",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "revenue / orders", "legendFormat": "__auto" }
   ]
  }
 ]
}