
# From rancher app form
customFqdn: "from.rancher.app.questions"
customName: "from.rancher.app.questions"
customEmail: "from.rancher.app.questions"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "bakery-as-a-service"

directus:
  key: "replace-with-random-value"
  secret: "replace-with-random-value"
  admin:
    email: "admin@example.com"
    password: "admin"

