
# Main chart config
clusterDomain: "caas-0024.dev.austrianopencloudcommunity.org"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "bakery-as-a-service"

directus:
  key: "replace-with-random-value"
  secret: "replace-with-random-value"
  admin:
    email: "admin@example.com"
    password: "admin"

# From rancher app form
customSubdomain: "baas"
customName: "BaaS Demo"
customEmail: "baas@example.com"
