
# Main chart config
clusterDomain: "caas-0024.dev.austrianopencloudcommunity.org"

imageTag: "main"

nameOverride: ""
fullnameOverride: "bakery-as-a-service"

directus:
  key: "replace-with-random-value"
  secret: "replace-with-random-value"

# From rancher app form
customSubdomain: "baas"
customName: "BaaS Demo"
customEmail: "admin@example.com"
customPassword: "admin"
