
# Main chart config
clusterDomain: "caas-0024.dev.austrianopencloudcommunity.org"

imageTag: "latest"

nameOverride: ""
fullnameOverride: "bakery-as-a-service"

# From rancher app form
customSubdomain: "baas"
customName: "BaaS Demo"
customEmail: "admin@example.com"
customPassword: "admin"
