apiVersion: apps/v1
kind: Deployment
metadata:
  name: baas-backend
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      servicename: baas-backend
  template:
    metadata:
      labels:
        servicename: baas-backend
    spec:
      containers:
      - env:
        - name: CUSTOM_NAME
          value: "{{ .Values.customName }}"
        - name: CUSTOM_EMAIL
          value: "{{ .Values.customEmail }}"
        - name: KEY
          value: "{{ .Values.directus.key }}"
        - name: SECRET
          value: "{{ .Values.directus.secret }}"
        - name: ADMIN_EMAIL
          value: "{{ .Values.customEmail }}"
        - name: ADMIN_PASSWORD
          value: "{{ .Values.customPassword }}"
        - name: DB_CLIENT
          value: "pg"
        - name: DB_HOST
          value: "service-baas-backend-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "directus"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: WEBSOCKETS_ENABLED
          value: "true"
        - name: REDIS_ENABLED
          value: "0" # TODO ENABLE again after REDIS_HOST is corrected
        - name: REDIS_HOST
          value: "valkey-master.default.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "replace-with-random-value"
        name: baas-backend
        image: directus/directus:10.10.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /server/health
            port: 8055
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: 512Mi
          requests:
            cpu: "50m"
            memory: 64Mi
        #volumeMounts:
        #- mountPath: /pv
        #  name: baas-backend
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      #volumes:
      #- name: baas-backend
      #  persistentVolumeClaim:
      #    claimName: baas-backend
