apiVersion: v1
kind: Service
metadata:
  name: service-baas-backend
spec:
  type: ClusterIP
  ports:
    - port: 8055 # exposed port reachable by other pods
      targetPort: 8055 # port inside container
      protocol: TCP
      name: http
  selector:
    servicename: baas-backend # Select member-pods of this service