apiVersion: v1
kind: Service
metadata:
  name: service-baas-document
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    servicename: baas-document
