apiVersion: apps/v1
kind: Deployment
metadata:
  name: baas-document
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      servicename: baas-document
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        servicename: baas-document
    spec:
      containers:
      - name: baas-document
        image: ghcr.io/austriandatalab/baas-document:main
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: 512Mi
          requests:
            cpu: "50m"
            memory: 64Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
