apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.document.name }}
spec:
  progressDeadlineSeconds: 60
  replicas: {{ .Values.document.replicaCount }}
  selector:
    matchLabels:
      servicename: {{ .Values.document.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        servicename: {{ .Values.document.name }}
    spec:
      containers:
      - name: {{ .Values.document.name }}
        image: {{ .Values.document.image.repository }}:{{ .Values.document.image.tag }}
        imagePullPolicy: {{ .Values.document.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: {{ .Values.document.service.port }}
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "{{ .Values.document.resources.limits.cpu }}"
            memory: {{ .Values.document.resources.limits.memory }}
          requests:
            cpu: "{{ .Values.document.resources.requests.cpu }}"
            memory: {{ .Values.document.resources.requests.memory }}
      restartPolicy: {{ .Values.document.restartPolicy }}
      terminationGracePeriodSeconds: {{ .Values.document.terminationGracePeriodSeconds }}
