apiVersion: apps/v1
kind: Deployment
metadata:
  name: baas-frontend
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      servicename: baas-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        servicename: baas-frontend
    spec:
      containers:
      - name: baas-frontend
        image: ghcr.io/austriandatalab/baas-frontend:main
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: 512Mi
          requests:
            cpu: "50m"
            memory: 64Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      env:
        - name: CUSTOM_FQDN
          value: "{{ .Values.customFqdn }}"
        - name: CUSTOM_NAME
          value: "{{ .Values.customName }}"
        - name: CUSTOM_EMAIL
          value: "{{ .Values.customEmail }}"
