# Ingress + TLS (with letsencrypt auto cert creation) to expose the frontend angular app
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "baas.labels" . | nindent 4 }}
  annotations:
    - cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
  name: baas-frontend-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: "{{ .Values.customSubdomain }}.{{ .Values.clusterDomain }}"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-baas-frontend
                port:
                  number: 8055
  tls:
    - hosts:
        - "{{ .Values.customSubdomain }}.{{ .Values.clusterDomain }}"
      secretName: tls-baas-frontend-ingress