apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-customer-config
data: 
  # Usage in Frontend: Add <script src="/assets/config.json"></script>, then use: window.customerDomain
  config.json: |
    {
      "appUrl": "//{{ .Values.customSubdomain }}-admin.{{ .Values.clusterDomain }}",
      "appName": "{{ .Values.customName }}",
      "customerEmail": "{{ .Values.customEmail }}"
    }
