apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-customer-config
data: 
  # Usage in Frontend: Add <script src="/assets/config.js"></script>, then use: window.customerDomain
  config.js: |
    customerDomain="{{ .Values.customDomain }}";
    customerName="{{ .Values.customName }}";
    customerEmail="{{ .Values.customEmail }}";
