apiVersion: v1
kind: Service
metadata:
  name: service-baas-backend-db
spec:
  type: ClusterIP
  ports:
    - port: 5432 # exposed port reachable by other pods
      targetPort: 5432 # port inside container
      protocol: TCP
      name: db-port
  selector:
    servicename: baas-backend-db # Select member-pods of this service