apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-baas-backend-db
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      servicename: service-baas-backend-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        servicename: service-baas-backend-db
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "directus"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        name: baas-backend
        image: "postgres:16.2"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
              - "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: 512Mi
          requests:
            cpu: "50m"
            memory: 64Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/
          name: baas-backend-db
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: baas-backend-db
        persistentVolumeClaim:
          claimName: baas-backend-db