name: Build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '19'
      - run: cd baas_strapi_docker && yarn install
      - run: cd baas_strapi_docker && yarn strapi ts:generate-types
      - run: cd baas_strapi_docker && yarn build
