name: Build and push the image

on:
  pull_request:
  push:
    branches:
      - main 
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: baas_backend

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        continue-on-error: true
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Build and conditionally push image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: baas-strapi-docker
          build-args: |
            FOO=bar
          # Push only on v* tags
          push: ${{ startsWith(github.event.ref, 'refs/tags/v') }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
